// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL3RefAODJ8ePgY65_maloUVBaxjz5uNg',
    appId: '1:829306801119:web:8c5bea097c7aa8c807926a',
    messagingSenderId: '829306801119',
    projectId: 'manufacturing-tracker-ethereum',
    authDomain: 'manufacturing-tracker-ethereum.firebaseapp.com',
    storageBucket: 'manufacturing-tracker-ethereum.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7uX5KcsgOggr0l8T0seHe1yqgZxXAJ-Q',
    appId: '1:829306801119:android:9ceec1ffad591c1307926a',
    messagingSenderId: '829306801119',
    projectId: 'manufacturing-tracker-ethereum',
    storageBucket: 'manufacturing-tracker-ethereum.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRqB8HtnB3FNbUYCiD-ga0TRIw8MM7IrQ',
    appId: '1:829306801119:ios:3bdbd4679845840507926a',
    messagingSenderId: '829306801119',
    projectId: 'manufacturing-tracker-ethereum',
    storageBucket: 'manufacturing-tracker-ethereum.appspot.com',
    iosClientId: '829306801119-l448r3pmo7pb5igtfn74aaup2fp2c2eq.apps.googleusercontent.com',
    iosBundleId: 'com.example.dapp',
  );
}
